/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foodorderingsystem;

import java.awt.Cursor;

public class Menu extends javax.swing.JFrame {

    Cursor cur = new Cursor(Cursor.HAND_CURSOR) ;
    
    public Menu() {
        initComponents();
        this.setLocation(500, 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        pnlPizza = new javax.swing.JPanel();
        lblPizza = new javax.swing.JLabel();
        imgPizza = new javax.swing.JLabel();
        pnlBurger = new javax.swing.JPanel();
        lblBurger = new javax.swing.JLabel();
        imgBurger = new javax.swing.JLabel();
        pnlShawarma = new javax.swing.JPanel();
        lblShawarma = new javax.swing.JLabel();
        imgShawarma = new javax.swing.JLabel();
        pnlBiryani = new javax.swing.JPanel();
        lblBiryani = new javax.swing.JLabel();
        imgBiryani = new javax.swing.JLabel();
        pnlDrinks = new javax.swing.JPanel();
        imgDrinks = new javax.swing.JLabel();
        lblDrinks = new javax.swing.JLabel();
        pnlDessert = new javax.swing.JPanel();
        lblDessert = new javax.swing.JLabel();
        imgDessert = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foodorderingsystem/Images/menu/menuPic.jpg"))); // NOI18N

        pnlPizza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlPizzaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlPizzaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlPizzaMouseExited(evt);
            }
        });

        lblPizza.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblPizza.setText("Pizza");

        imgPizza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foodorderingsystem/Images/menu/pizza.jpg"))); // NOI18N

        javax.swing.GroupLayout pnlPizzaLayout = new javax.swing.GroupLayout(pnlPizza);
        pnlPizza.setLayout(pnlPizzaLayout);
        pnlPizzaLayout.setHorizontalGroup(
            pnlPizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPizzaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPizza)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(imgPizza)
                .addContainerGap())
        );
        pnlPizzaLayout.setVerticalGroup(
            pnlPizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPizzaLayout.createSequentialGroup()
                .addGroup(pnlPizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPizzaLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(lblPizza))
                    .addComponent(imgPizza))
                .addGap(22, 22, 22))
        );

        pnlBurger.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlBurgerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlBurgerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlBurgerMouseExited(evt);
            }
        });

        lblBurger.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblBurger.setText("Burger");

        imgBurger.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foodorderingsystem/Images/menu/burger.jpg"))); // NOI18N

        javax.swing.GroupLayout pnlBurgerLayout = new javax.swing.GroupLayout(pnlBurger);
        pnlBurger.setLayout(pnlBurgerLayout);
        pnlBurgerLayout.setHorizontalGroup(
            pnlBurgerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBurgerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBurger)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imgBurger, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBurgerLayout.setVerticalGroup(
            pnlBurgerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBurgerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBurgerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBurgerLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(lblBurger))
                    .addComponent(imgBurger))
                .addContainerGap())
        );

        pnlShawarma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlShawarmaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlShawarmaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlShawarmaMouseExited(evt);
            }
        });

        lblShawarma.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblShawarma.setText("Shawarma");

        imgShawarma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foodorderingsystem/Images/menu/shawara.png"))); // NOI18N

        javax.swing.GroupLayout pnlShawarmaLayout = new javax.swing.GroupLayout(pnlShawarma);
        pnlShawarma.setLayout(pnlShawarmaLayout);
        pnlShawarmaLayout.setHorizontalGroup(
            pnlShawarmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlShawarmaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblShawarma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imgShawarma, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlShawarmaLayout.setVerticalGroup(
            pnlShawarmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlShawarmaLayout.createSequentialGroup()
                .addGroup(pnlShawarmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlShawarmaLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(lblShawarma))
                    .addGroup(pnlShawarmaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(imgShawarma)))
                .addContainerGap())
        );

        pnlBiryani.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlBiryaniMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlBiryaniMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlBiryaniMouseExited(evt);
            }
        });

        lblBiryani.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblBiryani.setText("Biryani");

        imgBiryani.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foodorderingsystem/Images/menu/biryani.png"))); // NOI18N

        javax.swing.GroupLayout pnlBiryaniLayout = new javax.swing.GroupLayout(pnlBiryani);
        pnlBiryani.setLayout(pnlBiryaniLayout);
        pnlBiryaniLayout.setHorizontalGroup(
            pnlBiryaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBiryaniLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBiryani)
                .addGap(18, 18, 18)
                .addComponent(imgBiryani)
                .addContainerGap())
        );
        pnlBiryaniLayout.setVerticalGroup(
            pnlBiryaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBiryaniLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBiryaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imgBiryani)
                    .addGroup(pnlBiryaniLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(lblBiryani)))
                .addContainerGap())
        );

        pnlDrinks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlDrinksMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlDrinksMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlDrinksMouseExited(evt);
            }
        });

        imgDrinks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foodorderingsystem/Images/menu/drinks.png"))); // NOI18N

        lblDrinks.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblDrinks.setText("Drinks");

        javax.swing.GroupLayout pnlDrinksLayout = new javax.swing.GroupLayout(pnlDrinks);
        pnlDrinks.setLayout(pnlDrinksLayout);
        pnlDrinksLayout.setHorizontalGroup(
            pnlDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDrinksLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDrinks)
                .addGap(34, 34, 34)
                .addComponent(imgDrinks)
                .addGap(28, 28, 28))
        );
        pnlDrinksLayout.setVerticalGroup(
            pnlDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDrinksLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgDrinks))
            .addGroup(pnlDrinksLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(lblDrinks))
        );

        pnlDessert.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlDessertMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlDessertMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlDessertMouseExited(evt);
            }
        });

        lblDessert.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblDessert.setText("Dessert");

        imgDessert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foodorderingsystem/Images/menu/dessert.png"))); // NOI18N

        javax.swing.GroupLayout pnlDessertLayout = new javax.swing.GroupLayout(pnlDessert);
        pnlDessert.setLayout(pnlDessertLayout);
        pnlDessertLayout.setHorizontalGroup(
            pnlDessertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDessertLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDessert)
                .addGap(18, 18, 18)
                .addComponent(imgDessert)
                .addContainerGap())
        );
        pnlDessertLayout.setVerticalGroup(
            pnlDessertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDessertLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDessertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDessertLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lblDessert))
                    .addComponent(imgDessert))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pnlDessert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pnlBiryani, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(pnlPizza, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlBurger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(76, 76, 76)
                            .addComponent(pnlDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(42, 42, 42)
                            .addComponent(pnlShawarma, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(pnlPizza, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(pnlBurger, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlShawarma, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlBiryani, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlDessert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlPizzaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPizzaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlPizzaMouseClicked

    private void pnlPizzaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPizzaMouseEntered
        imgPizza.setSize(150, 120);
        imgPizza.setCursor(cur);
        lblPizza.setCursor(cur);
    }//GEN-LAST:event_pnlPizzaMouseEntered

    private void pnlPizzaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPizzaMouseExited
        imgPizza.setSize(110,110);
    }//GEN-LAST:event_pnlPizzaMouseExited

    private void pnlBiryaniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBiryaniMouseClicked
        this.setVisible(false);
        Biryani b = new Biryani();
        b.setVisible(true);
    }//GEN-LAST:event_pnlBiryaniMouseClicked

    private void pnlBiryaniMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBiryaniMouseEntered
         imgBiryani.setSize(150, 100);
        imgBiryani.setCursor(cur);
        lblBiryani.setCursor(cur);
    }//GEN-LAST:event_pnlBiryaniMouseEntered

    private void pnlBiryaniMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBiryaniMouseExited
        imgBiryani.setSize(130, 90);
    }//GEN-LAST:event_pnlBiryaniMouseExited

    private void pnlBurgerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBurgerMouseClicked
        this.setVisible(false);
        Burgers bur = new Burgers();
        bur.setVisible(true);
    }//GEN-LAST:event_pnlBurgerMouseClicked

    private void pnlBurgerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBurgerMouseEntered
        imgBurger.setSize(150, 110);
        imgBurger.setCursor(cur);
        lblBurger.setCursor(cur);
    }//GEN-LAST:event_pnlBurgerMouseEntered

    private void pnlBurgerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBurgerMouseExited
        imgBurger.setSize(130, 100);
    }//GEN-LAST:event_pnlBurgerMouseExited

    private void pnlShawarmaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlShawarmaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlShawarmaMouseClicked

    private void pnlShawarmaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlShawarmaMouseEntered
       imgShawarma.setSize(150, 115);
        imgShawarma.setCursor(cur);
        lblShawarma.setCursor(cur);
    }//GEN-LAST:event_pnlShawarmaMouseEntered

    private void pnlShawarmaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlShawarmaMouseExited
       imgShawarma.setSize(125, 105);
    }//GEN-LAST:event_pnlShawarmaMouseExited

    private void pnlDessertMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDessertMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlDessertMouseClicked

    private void pnlDessertMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDessertMouseEntered
        imgDessert.setSize(140, 140);
        imgDessert.setCursor(cur);
        lblDessert.setCursor(cur);
    }//GEN-LAST:event_pnlDessertMouseEntered

    private void pnlDessertMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDessertMouseExited
        imgDessert.setSize(115, 130);
    }//GEN-LAST:event_pnlDessertMouseExited

    private void pnlDrinksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDrinksMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlDrinksMouseClicked

    private void pnlDrinksMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDrinksMouseExited
        imgDrinks.setSize(60, 130);
    }//GEN-LAST:event_pnlDrinksMouseExited

    private void pnlDrinksMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDrinksMouseEntered
        imgDrinks.setSize(70, 140);
        imgDrinks.setCursor(cur);
        lblDrinks.setCursor(cur);
    }//GEN-LAST:event_pnlDrinksMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgBiryani;
    private javax.swing.JLabel imgBurger;
    private javax.swing.JLabel imgDessert;
    private javax.swing.JLabel imgDrinks;
    private javax.swing.JLabel imgPizza;
    private javax.swing.JLabel imgShawarma;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblBiryani;
    private javax.swing.JLabel lblBurger;
    private javax.swing.JLabel lblDessert;
    private javax.swing.JLabel lblDrinks;
    private javax.swing.JLabel lblPizza;
    private javax.swing.JLabel lblShawarma;
    private javax.swing.JPanel pnlBiryani;
    private javax.swing.JPanel pnlBurger;
    private javax.swing.JPanel pnlDessert;
    private javax.swing.JPanel pnlDrinks;
    private javax.swing.JPanel pnlPizza;
    private javax.swing.JPanel pnlShawarma;
    // End of variables declaration//GEN-END:variables
}
